### ISSUE TITLE
Add example about how to get audio levels

### ISSUE THREAD

**Issue by ale0xb** [Coppertino/VOXHistogramView#1]
Hello, 

I'm trying to use your view but I'm struggling to get the audio levels required to make it work. I'm not using an external API like Soundcloud so I need to retrieve this data from somewhere. I checked BOSS Audio Engine but it is a paid option which I'd like to avoid if possible. 

Couldn't you illustrate better the process to get the json file (or better, the array of NSNumbers) using CoreAudio or similar? In my case I'd need to get this from a music audio file on iTunes Lib (MPMediaItem) but the example doesn't show how to do it.

**Comment by NickolaySheika** [comment]
Take a look at this - http://www.un4seen.com/forum/?topic=10910.msg76056#msg76056 and this - https://github.com/syedhali/EZAudio

**Comment by ale0xb** [comment]
Hello, 

Just passing by to leave my solution here, so others can benefit from it in the future:

I finally end up using [EZAudio](https://github.com/syedhali/EZAudio) and concretely, EZAudioFile.
One just have to instantiate one such object and call the utility method:
`- (void)getWaveformDataWithNumberOfPoints:(UInt32)numberOfPoints
                               completion:(EZAudioWaveformDataCompletionBlock)completion`
It returns two float arrays (one per channel) ready to be passed on to VOXHistogramControlView (needs to be converted to array of NSNumber first though).

Hope it helps! Thanks.
